### ISSUE TITLE
listing ingredients when none exist causes error

### ISSUE THREAD

**Issue by jcspeegs** [jcspeegs/barf_calc#9]
ugflows  ~  dev  barf_calc  ./barf_calc.py                                                                  SIGINT   master 
Welcome to BARFCalc!
(a)dd, (r)emove, (l)ist, (q)uit: l

Ingredients

Total Weight:   0.0

Mix
Traceback (most recent call last):
  File "/home/ugflows/dev/barf_calc/./barf_calc.py", line 144, in <module>
    main()
  File "/home/ugflows/dev/barf_calc/./barf_calc.py", line 140, in main
    barf_calc(presets)
  File "/home/ugflows/dev/barf_calc/./barf_calc.py", line 132, in barf_calc
    Food.display_meal()
  File "/home/ugflows/dev/barf_calc/./barf_calc.py", line 77, in display_meal
    cls.display_total_wt(cls._total_wt)
  File "/home/ugflows/dev/barf_calc/./barf_calc.py", line 54, in display_total_wt
    print(f'\t{category}:\t{wt[category]/wt["weight"]:>5.1%}')
ZeroDivisionError: float division by zero

**Comment by jcspeegs** [comment]
#13
